spring.application.name=catalog-service
server.port=8085
spring.datasource.url=jdbc:postgresql://localhost:5433/catalog
spring.datasource.username=catalog
spring.datasource.password=catalog
spring.jpa.hibernate.ddl-auto=update

