spring.application.name=inventory-service
server.port = 8086

spring.datasource.url=jdbc:postgresql://localhost:5431/inventory
spring.datasource.username=inventory
spring.datasource.password=inventory
spring.jpa.hibernate.ddl-auto=update


